name: campusvalore
favicon: null
layout_spectrum: 0.5638
typography_spectrum: 0.63888
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#161616'
    - '#f4e5de'
    - '#979cb0'
    - '#bcc2d0'
    - '#775539'
  brandStrength: 0.375
  lightness: 0.5625
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
