name: campusvalore
favicon: null
layout_spectrum: 0.5638
typography_spectrum: 0.63888
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f6f6f8'
    - '#18171c'
    - '#bcbab6'
    - '#018cca'
    - '#966e64'
  brandStrength: 0.375
  lightness: 0.5625
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
