name: campusvalore
favicon: null
layout_spectrum: 0.6161946314387023
typography_spectrum: 0.63888
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5651220364961773
  lightness: 0.40114578464999795
  saturation: 0.15783023973926902
  rhythmicContrast: 0.9869647766463459
purpose: []
